package utils

func GetTableTypes(t string) map[string]string {
	tableTypes := make(map[string]map[string]string)
	tableTypes["articles"] = map[string]string{
		"id":            "uint64",
		"uid":           "int",
		"oid":           "string",
		"time":          "int",
		"updtime":       "int",
		"type":          "int",
		"grade":         "int",
		"card_url":      "string",
		"category":      "string",
		"source":        "string",
		"title":         "string",
		"url":           "string",
		"tags":          "string",
		"images":        "string",
		"content":       "string",
		"flag":          "int",
		"mid":           "uint64",
		"hash":          "string",
		"cover":         "string",
		"lda_topic":     "string",
		"content_score": "int",
		"editor":        "string",
		"last_edited":   "int",
		"feeds":         "string",
		"cms_options":   "string",
		"created_time":  "int",
		"groupid":       "int",
		"summary":       "string",
	}
	tableTypes["related"] = map[string]string{
		"id":            "int",
		"oid":           "string",
		"mid":           "int",
		"type":          "int",
		"img_flag":      "int",
		"time":          "int",
		"created_time":  "int",
		"source":        "string",
		"content_score": "int",
		"hashcode":      "uint64",
		"tag":           "string",
		"tags":          "string",
		"op_tag":        "int",
		"titlehash":     "uint64",
		"title_seg":     "string",
		"lda_topic":     "string",
		"topics":        "string",
		"status":        "uint64",
		"display":       "string",
		"groupid":       "string",
		"image_hash":    "string",
		"source_id":     "int",
	}
	tableTypes["toutiao_user"] = map[string]string{
		"uid":          "int",
		"imei":         "string",
		"token":        "string",
		"time":         "int",
		"updtime":      "int",
		"level":        "int",
		"type":         "int",
		"device_type":  "int",
		"location":     "string",
		"location_sel": "string",
		"channels":     "string",
		"tags":         "string",
		"settings":     "string",
		"favor":        "string",
		"aid":          "string",
		"device_brand": "string",
		"device_model": "string",
		"device_ua":    "string",
		"wm":           "string",
		"version":      "string",
	}
	tableTypes["subscribe"] = map[string]string{
		"uid":       "int",
		"imei":      "string",
		"ctime":     "int",
		"type":      "int",
		"target_id": "string",
	}
	tableTypes["push_articles"] = map[string]string{
		"id":  			"int",
		"uid":  		"int",
		"mid":  		"uint64",
		"oid":  		"string",
		"url":  		"string",
		"status":  		"int",
		"time":  		"int",
		"grade":  		"int",
		"title":  		"string",
		"abstract":  	"string",
		"category":  	"string",
		"labels":  		"string",
		"source":  		"string",
		"updtime":  	"datetime",
		"content":  	"string",
		"TYPE":  		"int",
		"TAGS":  		"string",
		"push_time":  	"int",
		"push_rule":  	"string",
		"push_type":  	"int",
		"push_count":  	"int",
		"push_ok":  	"int",
		"push_click":  	"int",
	}

	if types, exists := tableTypes[t]; exists {
		return types
	} else {
		return nil
	}
}
